/**
 * Supply Chain Finance
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { ProductDetails } from './productDetails';


export interface PurchaseOrder {
    manufacturerName?: string;
    orderid?: number;
    poNumber?: number;
    createDate?: Date;
    issueDate?: Date;
    supplierName?: string;
    supplierAddrs?: string;
    /**
     * Organisation ID
     */
    delivryAddrs?: string;
    billingAddrs?: string;
    productDetails?: Array<ProductDetails>;
    grndTotal?: number;
    advPaymnt?: number;
    netPayable?: number;
    amtInWords?: string;
    /**
     * Order Status
     */
    status?: PurchaseOrder.StatusEnum;
}
export namespace PurchaseOrder {
    export type StatusEnum = 'approved' | 'rejected';
    export const StatusEnum = {
        Approved: 'approved' as StatusEnum,
        Rejected: 'rejected' as StatusEnum
    }
}
