/**
 * Supply Chain Finance
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


export interface ProductDetails {
    particularsOfGoodsService?: string;
    quantity?: number;
    unit?: string;
    unitPrice?: number;
    totalPrice?: number;
    vat?: number;
    tax?: number;
    grandTotal?: number;
    advancePayment?: number;
    totalPayable?: number;
    amountInWords?: string;
}
